config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pictures do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user
  validates :comment, length: { minimum: 3, maximum: 150 }
  validates :user_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :image_file_name, presence: true
  validates :user_id, presence: true
  has_attached_file :image, :styles => { :medium => "1000x1000>", :thumb => "300x300>" },
                    :default_url => ":style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def previous
    if self == self.class.last
      self.class.first
    else
      self.class.where("id > ?", id).first
    end
  end

  def next
    if self == self.class.first
      self.class.last
    else
      self.class.where("id < ?", id).last
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		if !user_signed_in?
			flash[:danger] = "You must be logged in to leave a comment"
			redirect_to new_user_session_path
		else
			@picture = Picture.find(params[:picture_id])
			@comment = @picture.comments.new(comment_params)
			@comment.user_id = current_user.id
			if @comment.save
				flash[:success] = "Comment successfully created"
				redirect_to picture_path(@picture)
			else
				@previous_picture = @picture.previous
				@next_picture = @picture.next
				render 'pictures/show'
			end
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@picture = Picture.find(@comment.picture_id)
		if !user_signed_in? || current_user.id != @comment.user_id
			flash[:danger] = "You cannot delete a comment you haven't posted"
			redirect_to picture_path(@picture)
		else
			@comment.destroy
			flash[:success] = 'Comment deleted successfully'
			redirect_to picture_path(@picture)
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:comment)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		@picture = Picture.find(params[:picture_id])
		Like.create(user_id: current_user.id, picture_id: params[:picture_id])
		redirect_to picture_path(@picture)
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  before_action :page_params, :only => :index

  def index
    @pictures = Picture.order(created_at: :desc).paginate(page: params[:page], :per_page => 12)
  end

  def new
    if current_user
      @picture = Picture.new
      @comment = Comment.new
    else
      flash[:danger] = "You must be logged in to add a picture"
      redirect_to new_user_session_path
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @comment = Comment.new(comment_params)
    @picture.user_id = current_user.id
    if @picture.save
      @comment.user_id = current_user.id
      @comment.picture_id = @picture.id
      @comment.save
      flash[:success] = "Picture successfully added"
      redirect_to picture_path(@picture)
    else
      render 'pictures/new'
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @previous_picture = @picture.previous
    @next_picture = @picture.next
    @comment = Comment.new
  end

  def destroy
    @picture = Picture.find(params[:id])
    if !user_signed_in? || current_user.id != @picture.user_id
      flash[:danger] = "You cannot delete a picture you haven't posted"
      redirect_to picture_path(@picture)
    else
      @picture.destroy
      flash[:success] = 'Picture deleted successfully'
      redirect_to pictures_path
    end
  end

  private

    def picture_params
      params.require(:picture).permit(:image) if params[:picture]
    end

    def comment_params
      params.require(:comment).permit(:comment)
    end

    def page_key
      (self.class.to_s + "_page").to_sym
    end

    def page_params
      if params[:page]
        session[page_key] = params[:page]
      elsif session[page_key]
        params[:page] = session[page_key]
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def find_useremail(id)
    User.find(id).email
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def time_since_created(time_created)
    return pluralize((((Time.now - time_created) / 3600).round.to_s), 'hour') + " ago" if (Time.now - time_created) < 84600
    return pluralize((((Time.now - time_created) / 86400).round.to_s), 'day') + " ago" if (Time.now - time_created) < 2678400
    return pluralize((((Time.now - time_created) / 2678400).round.to_s), 'month') + " ago" if (Time.now - time_created) < 31536000
    pluralize((((Time.now - time_created) / 31536000).round.to_s), 'year') + " ago"
  end

end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_error_messages.html.erb
<div id="error_explanation" >
  <p class="alert alert-danger"> <%= pluralize(object.errors.count, "error") %> prohibited the item from being posted:</p>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This website was built by Edward Byne using Ruby on Rails.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse" class="container">
  <div class="container">
    <div id="logo">
      <%= link_to image_tag("henrylogo.gif", id: "logopicture"), root_path %>
      <%= link_to "Henrygram", root_path, id: "logoname" %>
    </div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'View pictures', pictures_path %></li>
              <li><%= link_to 'Add a picture', new_picture_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagrammy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/main' %>
  </body>
</html>

app/views/pictures/_comment_form.html.erb
<%= form_for [picture, comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.submit 'Comment' %>
<% end %>

app/views/pictures/_comments.html.erb
<h2>Comments</h2>
<% if picture.comments.any? %>
  <ul id="comments">
    <% picture.comments.each do |comment| %>
        <% if comment.errors.none? %>
          <li>
            <%= find_useremail(comment.user_id) %>: <%= comment.comment %> (<%= time_since_created(comment.created_at) %>) 
            <% if user_signed_in? && current_user.id == comment.user_id %>
              | <%= link_to "Delete comment", picture_comment_path(picture, comment), method: :delete %>
            <% end %>
          </li> 
        <% end %>
    <% end %>
  </ul>
<% else %>
  <p>No comments</p>
<% end %>
<br>

app/views/pictures/_picture.html.erb
<h2 class="center">Picture added by <%= find_useremail(picture.user_id) %> (<%= time_since_created(picture.created_at) %>)</h2>
<%= image_tag picture.image.url(:medium), class: "main-pic center-block" %>
<br>
<p>
  <%= link_to "Like", picture_likes_path(picture), :method => :post, class: 'likes-link' %> | 
  <span class="likes_count"> <%= picture.likes.count %></span> Likes
  <% if user_signed_in? && current_user.id == picture.user_id %>
  <%= link_to "Delete picture", picture_path(picture), method: :delete, class: "delete-pic" %>
  <% end %>
</p>

app/views/pictures/index.html.erb
<% if @pictures.any? %>
  <div class="col-xs-12 col-sm-12 col-md-12 center pagination"><%= will_paginate %></div>
  <% @pictures.each do |picture| %>
    <div class="col-xs-6 col-sm-4 col-md-3">
      <%= link_to image_tag(picture.image.url(:thumb), class: "thumbnail center-block"), picture_path(picture), class: "picture-link" %>
    </div>
  <% end %>
<% else %>
  <div class="container">
    <h2>No pictures yet</h2>
  </div>
<% end %>
<div class="col-xs-12 col-sm-12 col-md-12 center">
  <br>
  <%= link_to 'Add a picture', new_picture_path, class: "btn btn-lg btn-primary add-picture-button" %>
</div>

app/views/pictures/new.html.erb
<%= render 'layouts/error_messages', object: @picture if @picture.errors.any? %>
<h2>Upload your picture</h2>
<%= form_for @picture, html: { multipart: true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= fields_for @comment do |fc| %>
    <%= fc.label :comment %>
    <%= fc.text_area :comment %>
  <% end %>
  <br><br>
  <%= f.submit 'Upload Picture' %>
<% end %>

app/views/pictures/show.html.erb
<%= render 'layouts/error_messages', object: @comment if @comment.errors.any? %>
<section>
  <div class="text-center picture-nav">
    <div class="btn-group" role="group" aria-label="...">
      <%= link_to "<span class=\"glyphicon glyphicon-chevron-left\"></span>".html_safe, picture_path(@previous_picture), class: "btn btn-default" %>
      <%= link_to "Back to index", pictures_path, class: "btn btn-default" %>
      <%= link_to "<span class=\"glyphicon glyphicon-chevron-right\"></span>".html_safe, picture_path(@next_picture), class: "btn btn-default" %>
    </div>
  </div><br>
  <%= render @picture %>
  <%= render 'pictures/comments', picture: @picture %>
  <%= render 'pictures/comment_form', picture: @picture, comment: @comment %>
</section>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>  
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>  
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
          <% if user_signed_in? %>
            <p class="navbar-text">
              Signed in as <%= "#{current_user.email}" %>
            </p>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>  
</header>

app/views/shared/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>